import { NextRequest, NextResponse } from 'next/server'

// Protected with a secret key — call with:
// curl -X POST https://your-site.com/api/admin/seed-global-grants \
//   -H "x-seed-key: YOUR_SEED_SECRET"

const GLOBAL_GRANTS = [
  // ── UNITED STATES ──────────────────────────────────────────────────────────
  {
    name: 'Grand Challenges in Global Health',
    funder: 'Bill & Melinda Gates Foundation',
    description: 'Supports innovative approaches to global health challenges including disease prevention, maternal health, and nutrition for underserved populations worldwide.',
    eligibility_criteria: 'Open to nonprofits, universities, and research institutions globally. Must address a specific global health challenge with measurable impact.',
    min_award: 100000, max_award: 1000000,
    deadline: '2026-09-30', application_url: 'https://gcgh.grandchallenges.org',
    sectors: ['health'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 1000000,
  },
  {
    name: 'Creativity and Free Expression Program',
    funder: 'Ford Foundation',
    description: 'Supports artists, cultural organisations, and nonprofits working to advance social justice through creative expression and storytelling.',
    eligibility_criteria: 'US-based nonprofits and international organisations working on social justice issues through arts and culture.',
    min_award: 50000, max_award: 500000,
    deadline: '2026-08-15', application_url: 'https://www.fordfoundation.org/work/our-grants',
    sectors: ['arts', 'other'], locations: ['United States', 'Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 500000,
  },
  {
    name: 'Health Care Access & Coverage Program',
    funder: 'Robert Wood Johnson Foundation',
    description: 'Funds organisations working to ensure all Americans have access to affordable, quality health care and to address health inequities.',
    eligibility_criteria: 'US-based nonprofits and public organisations. Must focus on health access, coverage, or equity.',
    min_award: 25000, max_award: 300000,
    deadline: '2026-10-01', application_url: 'https://www.rwjf.org/en/how-we-work/grants-explorer',
    sectors: ['health'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 300000,
  },
  {
    name: 'Children, Families & Communities Grants',
    funder: 'W.K. Kellogg Foundation',
    description: 'Supports programmes that improve the lives of vulnerable children and families, focusing on education, health, and economic security.',
    eligibility_criteria: 'US nonprofits serving children and families. Priority for organisations led by and serving communities of colour.',
    min_award: 25000, max_award: 250000,
    deadline: '2026-07-31', application_url: 'https://www.wkkf.org/grants',
    sectors: ['children', 'education', 'health'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 250000,
  },
  {
    name: '100&Change: A Competition for a Single Proposal',
    funder: 'MacArthur Foundation',
    description: 'Awards a single $100 million grant to fund a proposal that promises real and measurable progress in solving a critical problem of our time.',
    eligibility_criteria: 'Any organisation worldwide — nonprofit, for-profit, or government. Must propose a solution that is bold, durable, evidence-based, and verifiable.',
    min_award: 100000000, max_award: 100000000,
    deadline: '2026-12-01', application_url: 'https://www.macfound.org/programs/100change',
    sectors: ['other'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 100000000,
  },
  {
    name: 'Bloomberg Arts Internship',
    funder: 'Bloomberg Philanthropies',
    description: 'Funds paid summer internships at arts and cultural organisations for high school students from underrepresented communities.',
    eligibility_criteria: 'Arts and cultural nonprofits in Bloomberg Philanthropies program cities. Must be able to offer structured internship programmes.',
    min_award: 5000, max_award: 50000,
    deadline: '2026-11-15', application_url: 'https://www.bloomberg.org/arts',
    sectors: ['arts', 'education'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 50000,
  },
  {
    name: 'Bellagio Residency Program',
    funder: 'Rockefeller Foundation',
    description: 'Supports scholars, artists, policymakers, and practitioners whose work contributes to positive social and economic change globally.',
    eligibility_criteria: 'Individuals and teams engaged in scholarly, creative, or policy work with global impact. Must have demonstrated track record.',
    min_award: 10000, max_award: 100000,
    deadline: '2026-06-30', application_url: 'https://www.rockefellerfoundation.org/grants',
    sectors: ['other', 'education'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 100000,
  },
  {
    name: 'Children & Family Strengthening Grants',
    funder: 'Annie E. Casey Foundation',
    description: 'Supports nonprofits improving outcomes for vulnerable children in the US through family economic security, child welfare reform, and community investment.',
    eligibility_criteria: 'US-based nonprofits with proven track record serving disadvantaged children and families. Priority for systems-change work.',
    min_award: 50000, max_award: 400000,
    deadline: '2026-08-31', application_url: 'https://www.aecf.org/work/grants',
    sectors: ['children', 'education', 'homelessness'], locations: ['United States'],
    income_requirements: 'over_500k', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 400000,
  },
  {
    name: 'Arts & Culture Funding Initiative',
    funder: 'Knight Foundation',
    description: 'Invests in the arts to foster informed and engaged communities. Supports artists and arts organisations that bring people together.',
    eligibility_criteria: 'Nonprofits in Knight Foundation communities across the US. Must demonstrate impact on community engagement through arts.',
    min_award: 10000, max_award: 200000,
    deadline: '2026-09-15', application_url: 'https://knightfoundation.org/apply',
    sectors: ['arts'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 200000,
  },
  {
    name: 'Democracy Fund Innovation Grants',
    funder: 'Pew Charitable Trusts',
    description: 'Supports research and nonpartisan civic engagement initiatives that strengthen democratic institutions and informed public policy.',
    eligibility_criteria: 'US nonprofits and think tanks focused on nonpartisan policy research, civic engagement, or democratic reform.',
    min_award: 25000, max_award: 500000,
    deadline: '2026-07-15', application_url: 'https://www.pewtrusts.org/grants',
    sectors: ['other', 'education'], locations: ['United States'],
    income_requirements: 'over_500k', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 500000,
  },
  {
    name: 'Community Foundation Small Grants',
    funder: 'Community Foundations of the USA',
    description: 'Local community foundations across the US offer small grants for grassroots nonprofits addressing immediate community needs.',
    eligibility_criteria: 'Small nonprofits with annual income under $500,000. Must operate in the local community foundation service area.',
    min_award: 1000, max_award: 25000,
    deadline: '2026-06-01', application_url: 'https://www.cof.org/community-foundations',
    sectors: ['other', 'health', 'education'], locations: ['United States'],
    income_requirements: 'under_100k', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 25000,
  },
  {
    name: 'Environmental Defense Fund Climate Grants',
    funder: 'Environmental Defense Fund',
    description: 'Funds science-based environmental advocacy and community resilience projects addressing climate change and environmental justice.',
    eligibility_criteria: 'US nonprofits and advocacy organisations. Work must have clear environmental impact and measurable outcomes.',
    min_award: 20000, max_award: 150000,
    deadline: '2026-10-31', application_url: 'https://www.edf.org/grants',
    sectors: ['environment'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 150000,
  },
  {
    name: 'Homeless Prevention & Re-Housing Program',
    funder: 'US Department of Housing & Urban Development',
    description: 'Federal funding to prevent individuals and families from becoming homeless and to rapidly re-house those who become homeless.',
    eligibility_criteria: 'US nonprofits and local government agencies. Must provide direct housing assistance services to homeless or at-risk individuals.',
    min_award: 50000, max_award: 2000000,
    deadline: '2026-11-30', application_url: 'https://www.hud.gov/grants',
    sectors: ['homelessness'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 2000000,
  },
  {
    name: 'Disability Rights Advocacy Grants',
    funder: 'National Council on Disability',
    description: 'Supports nonprofits working on disability rights, inclusion, and accessibility across education, employment, and community life.',
    eligibility_criteria: 'US nonprofits led by or primarily serving people with disabilities. Must focus on systemic change.',
    min_award: 10000, max_award: 75000,
    deadline: '2026-08-01', application_url: 'https://ncd.gov',
    sectors: ['disability'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 75000,
  },
  {
    name: 'Educational Technology Innovation Grant',
    funder: 'Bill & Melinda Gates Foundation',
    description: 'Supports organisations developing and scaling innovative educational technology solutions for underserved students in the US.',
    eligibility_criteria: 'US nonprofits and social enterprises focused on K-12 or community college education. Must have evidence of impact.',
    min_award: 100000, max_award: 750000,
    deadline: '2026-09-01', application_url: 'https://www.gatesfoundation.org/about/how-we-work/grant-seekers',
    sectors: ['education'], locations: ['United States'],
    income_requirements: 'Any size', is_active: true,
    country: 'United States', region: 'North America', currency: 'USD', amount_usd: 750000,
  },

  // ── CANADA ────────────────────────────────────────────────────────────────
  {
    name: 'Canada Council Arts Grants',
    funder: 'Canada Council for the Arts',
    description: 'Provides funding to Canadian artists and arts organisations across all disciplines to create, share, and distribute Canadian arts.',
    eligibility_criteria: 'Canadian nonprofits and professional artists. Must be Canadian citizen or permanent resident. Work must have significant artistic merit.',
    min_award: 5000, max_award: 150000,
    deadline: '2026-07-01', application_url: 'https://canadacouncil.ca/funding',
    sectors: ['arts'], locations: ['Canada'],
    income_requirements: 'Any size', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 110000,
  },
  {
    name: 'Social Innovation Fund Canada',
    funder: 'McConnell Foundation',
    description: 'Supports social innovation initiatives that address systemic issues in Canadian communities, with a focus on Indigenous reconciliation and wellbeing.',
    eligibility_criteria: 'Canadian nonprofits and social enterprises. Priority for organisations working with Indigenous communities.',
    min_award: 25000, max_award: 200000,
    deadline: '2026-08-15', application_url: 'https://mcconnellfoundation.ca/grants',
    sectors: ['other', 'education', 'health'], locations: ['Canada'],
    income_requirements: 'Any size', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 148000,
  },
  {
    name: 'Inspirit Pluralism Grants',
    funder: 'Inspirit Foundation',
    description: 'Funds media, technology, and community initiatives that advance pluralism and reduce discrimination among young Canadians.',
    eligibility_criteria: 'Canadian nonprofits and media organisations engaging young people (15-30) on pluralism and social inclusion.',
    min_award: 10000, max_award: 100000,
    deadline: '2026-09-30', application_url: 'https://inspiritfoundation.org/apply',
    sectors: ['education', 'arts', 'other'], locations: ['Canada'],
    income_requirements: 'under_100k', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 74000,
  },
  {
    name: 'Community Resilience Fund',
    funder: 'Community Foundations of Canada',
    description: 'Supports local nonprofits in building community resilience through environmental sustainability, economic development, and social cohesion.',
    eligibility_criteria: 'Canadian registered charities. Must operate in a Community Foundations of Canada member community.',
    min_award: 5000, max_award: 50000,
    deadline: '2026-06-15', application_url: 'https://communityfoundations.ca',
    sectors: ['environment', 'other'], locations: ['Canada'],
    income_requirements: 'Any size', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 37000,
  },
  {
    name: 'Mental Health Innovation Grant',
    funder: 'Bell Let\'s Talk Initiative',
    description: 'Funds organisations delivering evidence-based mental health programmes and reducing stigma, with focus on youth and Indigenous populations.',
    eligibility_criteria: 'Canadian registered charities delivering mental health services. Must demonstrate community need and evidence-based approach.',
    min_award: 25000, max_award: 500000,
    deadline: '2026-10-15', application_url: 'https://letstalk.bell.ca/en/bell-lets-talk-community-fund',
    sectors: ['health', 'children'], locations: ['Canada'],
    income_requirements: 'Any size', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 370000,
  },
  {
    name: 'Environmental Stewardship Program',
    funder: 'Government of Canada — Environment',
    description: 'Supports community conservation projects protecting Canada\'s natural ecosystems, biodiversity, and climate resilience.',
    eligibility_criteria: 'Canadian nonprofits, Indigenous organisations, and community groups. Must have a conservation project with measurable outcomes.',
    min_award: 10000, max_award: 250000,
    deadline: '2026-07-31', application_url: 'https://www.canada.ca/en/environment-climate-change/services/environmental-funding.html',
    sectors: ['environment'], locations: ['Canada'],
    income_requirements: 'Any size', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 185000,
  },
  {
    name: 'Digital Equity Fund',
    funder: 'Inspirit Foundation',
    description: 'Bridges the digital divide by funding organisations that provide technology access and digital literacy training to marginalised communities.',
    eligibility_criteria: 'Canadian nonprofits serving communities with limited digital access. Priority for rural, Indigenous, and newcomer communities.',
    min_award: 5000, max_award: 75000,
    deadline: '2026-08-01', application_url: 'https://inspiritfoundation.org/apply',
    sectors: ['education', 'other'], locations: ['Canada'],
    income_requirements: 'under_100k', is_active: true,
    country: 'Canada', region: 'North America', currency: 'CAD', amount_usd: 55500,
  },

  // ── AUSTRALIA ─────────────────────────────────────────────────────────────
  {
    name: 'Australian Communities Foundation Grants',
    funder: 'Australian Communities Foundation',
    description: 'Provides grants to Australian nonprofits working across social, environmental, arts, and community development causes.',
    eligibility_criteria: 'DGR-endorsed Australian nonprofits. Must align with one of ACF\'s philanthropic funds. Local community impact required.',
    min_award: 5000, max_award: 100000,
    deadline: '2026-08-31', application_url: 'https://www.acf.org.au/grants',
    sectors: ['other', 'environment', 'arts'], locations: ['Australia'],
    income_requirements: 'Any size', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 65000,
  },
  {
    name: 'Cycle of Disadvantage Program',
    funder: 'Paul Ramsay Foundation',
    description: 'Funds transformative solutions that break the cycle of disadvantage in Australia, focusing on education, employment, and community wellbeing.',
    eligibility_criteria: 'Australian nonprofits with strong evidence base. Must address root causes of entrenched disadvantage, not symptoms.',
    min_award: 100000, max_award: 2000000,
    deadline: '2026-11-01', application_url: 'https://paulramsayfoundation.org.au/grants',
    sectors: ['education', 'health', 'homelessness'], locations: ['Australia'],
    income_requirements: 'over_500k', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 1300000,
  },
  {
    name: 'Perpetual Impact Philanthropy',
    funder: 'Perpetual Foundation',
    description: 'Supports Australian charities tackling social disadvantage and delivering services that create lasting community impact.',
    eligibility_criteria: 'ACNC-registered Australian charities. Must demonstrate track record of impact and financial sustainability.',
    min_award: 10000, max_award: 150000,
    deadline: '2026-09-15', application_url: 'https://www.perpetual.com.au/advice/perpetual-foundation',
    sectors: ['other', 'health', 'children'], locations: ['Australia'],
    income_requirements: 'Any size', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 97500,
  },
  {
    name: 'Myer Foundation Community Grants',
    funder: 'Myer Foundation',
    description: 'Invests in Australian organisations that advance education, arts, human rights, and sustainable environment.',
    eligibility_criteria: 'DGR-endorsed Australian nonprofits. Applications must align with Myer Foundation\'s current priority areas. Smaller grants for emerging organisations.',
    min_award: 5000, max_award: 75000,
    deadline: '2026-07-31', application_url: 'https://www.myerfoundation.org.au/grants',
    sectors: ['education', 'arts', 'environment'], locations: ['Australia'],
    income_requirements: 'Any size', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 48750,
  },
  {
    name: 'Vincent Fairfax Ethics in Leadership Grant',
    funder: 'Vincent Fairfax Family Foundation',
    description: 'Supports Australian nonprofits that embed ethical leadership and good governance into their organisation and sector.',
    eligibility_criteria: 'Australian nonprofits demonstrating strong governance. Must be working on leadership development, ethics, or good governance programmes.',
    min_award: 10000, max_award: 100000,
    deadline: '2026-10-01', application_url: 'https://www.vfff.org.au',
    sectors: ['education', 'other'], locations: ['Australia'],
    income_requirements: 'Any size', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 65000,
  },
  {
    name: 'ACNC Capacity Building Grants',
    funder: 'Australian Charities and Not-for-profits Commission',
    description: 'Builds the operational capacity of small and medium Australian charities through funding for governance, systems, and staff development.',
    eligibility_criteria: 'ACNC-registered charities with annual income under AUD 1 million. Must demonstrate capacity building need.',
    min_award: 5000, max_award: 30000,
    deadline: '2026-06-30', application_url: 'https://www.acnc.gov.au/grants',
    sectors: ['other'], locations: ['Australia'],
    income_requirements: 'under_100k', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 19500,
  },
  {
    name: 'Indigenous Community Development Fund',
    funder: 'Australian Government — NIAA',
    description: 'Supports Indigenous-led organisations delivering community development initiatives across Australia\'s remote and regional communities.',
    eligibility_criteria: 'Aboriginal and Torres Strait Islander organisations. Must be community-led with strong local governance.',
    min_award: 20000, max_award: 500000,
    deadline: '2026-09-30', application_url: 'https://www.niaa.gov.au/grants',
    sectors: ['other', 'health', 'education'], locations: ['Australia'],
    income_requirements: 'Any size', is_active: true,
    country: 'Australia', region: 'Asia Pacific', currency: 'AUD', amount_usd: 325000,
  },

  // ── EUROPE ────────────────────────────────────────────────────────────────
  {
    name: 'European Cultural Foundation Grants',
    funder: 'European Cultural Foundation',
    description: 'Supports cultural projects that cross borders and bring Europeans together, focusing on civic engagement and inclusive societies.',
    eligibility_criteria: 'European nonprofits and cultural organisations. Projects must involve at least two European countries. Must address social or cultural challenges.',
    min_award: 10000, max_award: 150000,
    deadline: '2026-10-15', application_url: 'https://culturalfoundation.eu/apply',
    sectors: ['arts', 'other'], locations: ['Europe'],
    income_requirements: 'Any size', is_active: true,
    country: 'Netherlands', region: 'Europe', currency: 'EUR', amount_usd: 163000,
  },
  {
    name: 'Open Society Civil Society Fund',
    funder: 'Open Society Foundations',
    description: 'Funds civil society organisations advancing human rights, democracy, and social justice across Europe and globally.',
    eligibility_criteria: 'Nonprofits working on human rights, justice reform, or democratic governance. Must demonstrate independence and civil society accountability.',
    min_award: 50000, max_award: 500000,
    deadline: '2026-08-30', application_url: 'https://www.opensocietyfoundations.org/grants',
    sectors: ['other'], locations: ['Europe', 'Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'Germany', region: 'Europe', currency: 'EUR', amount_usd: 545000,
  },
  {
    name: 'Porticus Social Justice Grants',
    funder: 'Porticus Foundation',
    description: 'Supports organisations working on social justice, faith, education, and environment with a focus on sustainable systemic change.',
    eligibility_criteria: 'Nonprofits in Europe, Latin America, Africa, and Asia. Must align with Porticus strategic priorities. No cold applications — by invitation or introduction.',
    min_award: 50000, max_award: 1000000,
    deadline: '2026-12-01', application_url: 'https://www.porticus.com/en/applying-for-support',
    sectors: ['education', 'environment', 'other'], locations: ['Europe', 'Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'Netherlands', region: 'Europe', currency: 'EUR', amount_usd: 1090000,
  },
  {
    name: 'Wellcome Trust International Research Grants',
    funder: 'Wellcome Trust',
    description: 'Funds health research and innovation with global impact, supporting scientists, researchers, and public health organisations worldwide.',
    eligibility_criteria: 'Research institutions, universities, and public health nonprofits globally. Must propose rigorous research addressing a significant health challenge.',
    min_award: 100000, max_award: 5000000,
    deadline: '2026-09-01', application_url: 'https://wellcome.org/grant-funding',
    sectors: ['health'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United Kingdom', region: 'Europe', currency: 'GBP', amount_usd: 6350000,
  },
  {
    name: 'Horizon Europe Social Innovation Fund',
    funder: 'European Commission',
    description: 'The EU\'s flagship programme for research and innovation. Funds collaborative projects addressing Europe\'s societal challenges.',
    eligibility_criteria: 'Consortia of at least 3 organisations from different EU member states. Must address EU policy priorities. Organisations of all types eligible.',
    min_award: 500000, max_award: 5000000,
    deadline: '2026-11-15', application_url: 'https://ec.europa.eu/info/funding-tenders/opportunities',
    sectors: ['other', 'environment', 'health', 'education'], locations: ['Europe'],
    income_requirements: 'over_500k', is_active: true,
    country: 'Germany', region: 'Europe', currency: 'EUR', amount_usd: 5450000,
  },
  {
    name: 'Climate Reality Arts & Environment Grants',
    funder: 'European Climate Foundation',
    description: 'Supports organisations using arts, media, and civic engagement to accelerate Europe\'s transition to a net-zero economy.',
    eligibility_criteria: 'European nonprofits and media organisations working on climate communication and civic engagement. Must have measurable advocacy outcomes.',
    min_award: 50000, max_award: 500000,
    deadline: '2026-07-01', application_url: 'https://europeanclimate.org/grants',
    sectors: ['environment', 'arts'], locations: ['Europe'],
    income_requirements: 'Any size', is_active: true,
    country: 'Netherlands', region: 'Europe', currency: 'EUR', amount_usd: 545000,
  },

  // ── GLOBAL / INTERNATIONAL ────────────────────────────────────────────────
  {
    name: 'UNDP Small Grants Programme',
    funder: 'United Nations Development Programme',
    description: 'Provides grants to civil society organisations and local communities for projects addressing biodiversity, climate change, land degradation, and persistent organic pollutants.',
    eligibility_criteria: 'Community-based organisations and nonprofits in developing countries. Projects must have clear environmental impact and community benefit.',
    min_award: 5000, max_award: 50000,
    deadline: '2026-07-15', application_url: 'https://sgp.undp.org/apply-for-grant',
    sectors: ['environment', 'other'], locations: ['Global'],
    income_requirements: 'under_100k', is_active: true,
    country: 'Global', region: 'Global', currency: 'USD', amount_usd: 50000,
  },
  {
    name: 'World Bank Development Marketplace',
    funder: 'World Bank',
    description: 'A global competition that identifies and funds innovative early-stage development projects with potential for broad societal impact.',
    eligibility_criteria: 'Civil society organisations and social enterprises in developing countries. Must propose an innovative solution to a development challenge.',
    min_award: 10000, max_award: 200000,
    deadline: '2026-09-30', application_url: 'https://www.worldbank.org/en/programs/development-marketplace',
    sectors: ['health', 'education', 'environment', 'other'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'Global', region: 'Global', currency: 'USD', amount_usd: 200000,
  },
  {
    name: 'Comic Relief International Grants',
    funder: 'Comic Relief',
    description: 'Funds organisations tackling poverty and social injustice in the UK and internationally, focusing on the most vulnerable people.',
    eligibility_criteria: 'UK-registered charities with international programmes, or overseas registered organisations. Must demonstrate direct work with people living in poverty.',
    min_award: 10000, max_award: 200000,
    deadline: '2026-08-01', application_url: 'https://www.comicrelief.com/applying-for-grants',
    sectors: ['other', 'health', 'education', 'children'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'United Kingdom', region: 'Global', currency: 'GBP', amount_usd: 254000,
  },
  {
    name: 'Aga Khan Foundation International Grants',
    funder: 'Aga Khan Foundation',
    description: 'Supports sustainable, high-quality programmes in health, education, rural development, and civil society strengthening in developing countries.',
    eligibility_criteria: 'Local nonprofits in AKF programme countries (East Africa, South Asia, Central Asia, Middle East, and Europe). Must align with AKF strategic priorities.',
    min_award: 50000, max_award: 500000,
    deadline: '2026-10-31', application_url: 'https://www.akdn.org/agency/akf',
    sectors: ['health', 'education', 'other'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'Global', region: 'Global', currency: 'USD', amount_usd: 500000,
  },
  {
    name: 'USAID Community Development Grants',
    funder: 'USAID',
    description: 'Funds local organisations delivering democracy, health, economic growth, and humanitarian assistance programmes in developing countries.',
    eligibility_criteria: 'Local NGOs and civil society organisations in USAID-eligible countries. Must have experience managing development programmes and strong accountability systems.',
    min_award: 25000, max_award: 1000000,
    deadline: '2026-11-30', application_url: 'https://www.grants.gov/search-grants?agencyCode=USAID',
    sectors: ['health', 'education', 'environment', 'other'], locations: ['Global'],
    income_requirements: 'Any size', is_active: true,
    country: 'Global', region: 'Global', currency: 'USD', amount_usd: 1000000,
  },
  {
    name: 'Children Investment Fund Foundation',
    funder: 'CIFF',
    description: 'Invests in evidence-based programmes improving the lives of children in developing countries — focusing on nutrition, health, education, and climate.',
    eligibility_criteria: 'International NGOs and research institutions. Must demonstrate rigorous evidence base and potential for scale. By invitation or expression of interest.',
    min_award: 500000, max_award: 10000000,
    deadline: '2026-12-15', application_url: 'https://ciff.org/apply-for-funding',
    sectors: ['children', 'health', 'education', 'environment'], locations: ['Global'],
    income_requirements: 'over_500k', is_active: true,
    country: 'United Kingdom', region: 'Global', currency: 'GBP', amount_usd: 12700000,
  },
  {
    name: 'Global Environment Facility Small Grants',
    funder: 'Global Environment Facility',
    description: 'Provides grants to civil society and community organisations for environmental projects delivering global benefits at the local level.',
    eligibility_criteria: 'NGOs and community organisations in eligible developing countries. Projects must address at least one GEF focal area: biodiversity, climate, chemicals, or land degradation.',
    min_award: 5000, max_award: 50000,
    deadline: '2026-08-15', application_url: 'https://www.thegef.org/partners/ngos/small-grants',
    sectors: ['environment'], locations: ['Global'],
    income_requirements: 'under_100k', is_active: true,
    country: 'Global', region: 'Global', currency: 'USD', amount_usd: 50000,
  },
]

export async function POST(req: NextRequest) {
  const seedKey = req.headers.get('x-seed-key')
  if (seedKey !== process.env.SEED_SECRET) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
  }

  try {
    const { createClient } = await import('@supabase/supabase-js')
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )

    const { data, error } = await supabase
      .from('grants')
      .insert(GLOBAL_GRANTS)
      .select('id')

    if (error) {
      console.error('Seed error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({
      ok: true,
      inserted: data?.length ?? 0,
      countries: [...new Set(GLOBAL_GRANTS.map(g => g.country))],
    })
  } catch (err) {
    console.error('Seed error:', err)
    return NextResponse.json({ error: 'Seed failed' }, { status: 500 })
  }
}
